[build]
    ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../devconnect ../lib"
    command = "yarn build"
    publish = ".next"

[functions]
  included_files = ["src/content/**/*"]

[[plugins]]
    package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/grants"
  to = "https://esp.ethereum.foundation/devcon-grants"
  status = 302
  force = true