name: Prepare website content for AI

on:
  push:
    branches:
      - dev

jobs:
  build:
    defaults:
      run:
        working-directory: ./devcon
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn

      - name: Create env file
        run: |
          touch .env
          echo OPEN_AI_KEY='${{ secrets.OPEN_AI_KEY }}' >> .env

      - name: Run script
        run: yarn ai-content-sync
