name: Pretalx Sync

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "20"
      - run: yarn install
      - run: yarn sync:pretalx
        env:
          PRETALX_API_KEY: ${{ secrets.PRETALX_API_KEY }}
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "[action] Pretalx Sync"
