name: Pretalx Sync

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: ./devcon-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "20"
      - run: yarn install
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
      - run: yarn sync:pretalx
        env:
          PRETALX_API_KEY: ${{ secrets.PRETALX_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "[action] Pretalx Sync"
